-- SQL migration
ALTER TABLE field_templates
ADD COLUMN IF NOT EXISTS description TEXT,
ADD COLUMN IF NOT EXISTS is_visible BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS position INTEGER DEFAULT 0 NOT NULL;
